apiVersion: apps/v1
kind: Deployment
metadata:
    name: figlet-deploy
    labels:
        env: staging
spec:
    replicas: 3
    selector:
        matchLabels:
            env: staging
    template:
       metadata:
            labels:
                env: staging
       spec:
            containers:
            - name: figlet-deploy
              image: bakulgupta/figlet:v2
